/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package stage2_BranchAndBound;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
/**
 *
 * @author LENOVO
 */
public class stage2_medium extends javax.swing.JFrame {
    
    public int sec = 0;
    public int min =0;
    public Timer time ;  

    /**
     * Creates new form stage2
     */
    public stage2_medium() {
        initComponents();
        jPanel2.setVisible(true);
      //   Home.image(jLabel9);
         
          setLocationRelativeTo(this);
        time = new Timer(1000,new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) 
            {  
             jLabel3.setText(String.valueOf(min));
             jLabel4.setText(String.valueOf(sec));
             if(sec==60)
                {
                    sec = 0 ; 
                    min ++ ; 
                }
             if(min == 1 )
                    {
                        time.stop();
                        JOptionPane.showMessageDialog(null, "Time Over !! votre score 0","Attention !!!" , 2);
                    }
             sec++; 
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane6 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 796));
        setSize(new java.awt.Dimension(1200, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton8.setText("start");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jScrollPane8.setViewportView(jTextPane4);

        jPanel2.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 330, 260));

        jScrollPane9.setViewportView(jList3);

        jPanel2.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(907, 336, 60, 270));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("choisir vos piquets");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 310, 115, -1));

        jScrollPane10.setViewportView(jList4);

        jPanel2.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 336, 50, 270));

        jButton9.setText(">>");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 490, 48, -1));

        jButton10.setText("<<");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 520, 48, -1));

        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton11.setText("Valider ");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 630, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 102));
        jLabel7.setText("Score");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 830, -1));

        jTextPane5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextPane5.setForeground(new java.awt.Color(255, 0, 204));
        jScrollPane1.setViewportView(jTextPane5);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 210, 150));

        jLabel8.setFont(new java.awt.Font("Snap ITC", 1, 70)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("level 2");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 360, 100));

        jButton12.setText("Home");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 660, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText(":");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 10, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 19, 18));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 20, 20));

        jScrollPane3.setBackground(new java.awt.Color(242, 242, 242));
        jScrollPane3.setToolTipText("");

        jTextPane6.setBackground(new java.awt.Color(172, 67, 67,0));
        jTextPane6.setBorder(null);
        jTextPane6.setFont(new java.awt.Font("Source Code Pro Light", 0, 18)); // NOI18N
        jTextPane6.setText("Pour passer ce stage vous dever Gramper un Montagne .  un circuit de piquets (de differentes couleurs ) est deja place .  vous dever atteindre le sommet parcourant la distance minimale tout en collectant les piquets .Mais attention , l'un des couleur est infecté c'est dangereux de le prendre . ");
        jScrollPane3.setViewportView(jTextPane6);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 830, 140));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 160, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("jLabel1");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
      //  jPanel1.setVisible(false );
        jPanel2.setVisible(true );
        
        
        /*
        */
         
        
    }//GEN-LAST:event_formWindowOpened
DefaultListModel model2 = new DefaultListModel()  ; 
DefaultListModel model = new DefaultListModel()  ;
DefaultListModel model3 = new DefaultListModel()  ; 
DefaultListModel model4 = new DefaultListModel()  ; 
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        
        // les initialisations 
        sec = 0 ; 
        min = 0;
        time.start();
        probleme.initialiser();
        model3.clear();
        model4.clear();
       
       
        
        // affectation des parametres de resolution
        int nbPiquet  = 7 ;
        int startPiquet = 2;
        destination = 3 ; 
        probleme.nbPiquets = nbPiquet ;        
        probleme.startPiquet = startPiquet ;
        probleme.generateGraph(nbPiquet);
        probleme.generateColors(nbPiquet);
        couleureInterdite  = pick_danger_color(startPiquet,destination, nbPiquet); 
        
       
      
        // remplissage par toutes les piquets existantes + affichages des donnees nessecaires (naarach nektebha)
        for (int i= 1 ; i<= probleme.nbPiquets ; i++)
            model3.addElement(i+"");
        
        jList3.setModel(model3); 
        jTextPane5.setText("la couleur  "+ probleme.affect_color(probleme.couleur.get(couleureInterdite)) + " est mortelle !! ");
        jTextPane4.setText(probleme.showMountain());
        jLabel1.setText("Piquet De Depart :  "+startPiquet);
        jLabel2.setText("Destibation :"+destination);
        // resolution
        probleme.solution(startPiquet, probleme.couleur.get(couleureInterdite) , destination);
        
        
        // affichage resultat
       
        jButton11.setVisible(true);
       
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
          String n = jList3.getSelectedValue() ; 
        model4.addElement(n);
        jList4.setModel(model4);
        model3.removeElement(n);
        jList3.setModel(model3);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
         String n = jList4.getSelectedValue()  ; 
        model3.addElement(n);
        jList3.setModel(model3);
         model4.removeElement(n);
        jList4.setModel(model4);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        try{
         time.stop();
         ArrayList<Integer> cyclePlayer = new ArrayList<>();
         ArrayList<String> cyclePlayers = new ArrayList<>();
         int n = model4.getSize();
         for (int i=0  ; i< n ; i++)
         {
             cyclePlayers.add( model4.get(i).toString()); 
         }
         for(int i =0 ; i<cyclePlayers.size() ; i++)
             cyclePlayer.add(Integer.parseInt(cyclePlayers.get(i)));
         
         /*cyclePlayer.add(1) ; 
         cyclePlayer.add(3) ; 
         cyclePlayer.add(5) ; */
         long costPlayer = probleme.calculate_cost(cyclePlayer) ; 
         long cost = probleme.calculate_cost((ArrayList<Integer>) probleme.finalCycle) ; 
         
         
         if(cyclePlayer.isEmpty())
             jLabel7.setText("Vous etes encore au point de depart!! score : 0");
         else if(cyclePlayer.equals(probleme.finalCycle))
         {
          jLabel7.setText("Brovo , votre circuit est minimal ,  score : 100");
          score = 100 ;
         }
         else if (cyclePlayer.contains(couleureInterdite+1))
            JOptionPane.showMessageDialog(null, "vous avez ete tuer par le poinson du piquet "+ (couleureInterdite+1) +" !! score : 0","Sad for you" , 2);
        
         // else if(cyclePlayer.get(0 )!= probleme.startPiquet)
//                 jLabel2.setText("vous n'avais pas commencé par le point de depart !! score : 0");
         else
         {
             if(cyclePlayer.get(cyclePlayer.size()-1) == destination)
             {  
                 score = 100 - Math.abs((int)(costPlayer - cost) ); 
                 jLabel7.setText("vous atteint la destination , mais pas en fesant le circuit minimal ! score : "+ score);
               
                 
             }
             else if (cyclePlayer.contains(destination))
             {
                 jLabel7.setText("vous avez depassé la destination !! score : 0");
             }
             else 
                 jLabel7.setText("vous n'avais pas atteint la destination !! score : 0");
         }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "vous avez ete tuer par le poinson du piquet "+ (couleureInterdite+1) +" !! score : 0","Sad for you" , 2);
        }
        
        jButton11.setVisible(false);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        Home a = new Home();
        a.show();
        this.hide();
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public  int  destination  , level , couleureInterdite;  
    public float score = stage2.score ; 
    public int pick_danger_color(int start , int destination , int nb )
    {
        int couleureInterdite = 11 ,  i=0 ; 
        boolean find = false ;
        while ((i<nb) && (!find))
        {
            if ((probleme.couleur.get(start-1) != probleme.couleur.get(i)) && (probleme.couleur.get(destination-1) != probleme.couleur.get(i)))
            {
                couleureInterdite = i ; 
                find = true ; 
            }
            else 
                i++; 
        }
        return couleureInterdite  ; 
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stage2_medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stage2_medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stage2_medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stage2_medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stage2_medium().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JTextPane jTextPane6;
    // End of variables declaration//GEN-END:variables

}
